//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeBuild.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeBuild.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 生成成功，目前文件路径在 : C盘Temp文件中 的本地化字符串。
        /// </summary>
        internal static string Mains_BuildCodeBtnClick_ {
            get {
                return ResourceManager.GetString("Mains_BuildCodeBtnClick_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 抱歉您并没有选择表名或数据库名 的本地化字符串。
        /// </summary>
        internal static string Mains_BuildCodeBtnClick_抱歉您并没有选择表名 {
            get {
                return ResourceManager.GetString("Mains_BuildCodeBtnClick_抱歉您并没有选择表名", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测试成功 的本地化字符串。
        /// </summary>
        internal static string Mains_button1_Click_测试成功 {
            get {
                return ResourceManager.GetString("Mains_button1_Click_测试成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择数据库 的本地化字符串。
        /// </summary>
        internal static string Mains_ValueChangeTextRangeValue_选择数据库 {
            get {
                return ResourceManager.GetString("Mains_ValueChangeTextRangeValue_选择数据库", resourceCulture);
            }
        }
    }
}
